version: '3'

services:
  message-service:
    build: ./message-service
    volumes:
      - ./message-service:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 5050:5050

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root

  user-service:
    build: ./user-service
    volumes:
      - ./user-service:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 5051:5051
    depends_on:
      - db
      - message-service

  chat-message-service:
    build: ./chat-message-service
    volumes:
      - ./chat-message-service:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 5052:5052
    depends_on:
      - db
      - message-service

  frontend-service:
    build: ./frontend-service
    volumes:
      - ./frontend-service:/usr/src/app
      - ~/.m2:/root/.m2
    ports:
      - 3000:3000
      - 5053:5053
    depends_on:
      - message-service
      - user-service
      - chat-message-service